version: '3.8'

services:
  user-service:
    build: ./user-service
    ports:
      - "3001:3001"
    networks:
      - micro-net

  product-service:
    build: ./product-service
    ports:
      - "3002:3002"
    depends_on:
      - user-service
    networks:
      - micro-net

networks:
  micro-net:
    driver: bridge
